# Generated by Django 5.1.7 on 2025-04-15 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Номер должен быть в формате: '+79991234567' (ровно 11 цифр)", regex='^\\+7\\d{10}$')], verbose_name='Номер телефона'),
        ),
    ]
