# Generated by Django 5.1.7 on 2025-04-11 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='service',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='core.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='service',
            name='prices',
            field=models.ManyToManyField(blank=True, to='core.price', verbose_name='Цены'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicetype', verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('hour', 'Час'), ('day', 'День')], default='hour', max_length=10, verbose_name='Тип длительности'),
        ),
    ]
