# Generated by Django 5.1.7 on 2025-04-07 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.servicetype', verbose_name='Вид услуги'),
        ),
    ]
